version: '3'

services:
  db_test:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=testuser
      - POSTGRES_DB=potentiel_test
    restart: always
    ports:
      - 5433:5432
