name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm test
      - run: npm run test-int-init-db
      - run: npm run test-int
      - run: npm run build
      - uses: 47ng/actions-clever-cloud@v1
        with:
          appID: app_eeb6121a-65e3-4085-b85a-a56c986c680c
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
